openapi: 3.0.3

info:
  version: 1.0.0
  title: Balance Tracker API
  description: 'Balance Tracker API, -POST Balance Snapshot, -POST Balance WRITE Operation: Withdrawal, Deposit'


tags:
  - name: greeting
    description: Hello World
  - name: balanceTracker
    description: (internal)API for our own ProdSummary

servers:
  - url: http://localhost:{port}/
    description: local dev environment
    variables:
      port:
        default: '8018'

paths:
  /balance/snapshot:
    post:
      tags:
        - balance
      summary: post a snapshot
      operationId: saveBalanceSnapshot
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/BalanceSnapshotDTO'
      responses:
        '201':
          description: success


  /hello:
    get:
      tags:
        - greeting
      summary: greeting List
      operationId: getGreetings
      responses:
        '200':
          description: success
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/GreetingDTO'
        '400':
          $ref: '#/components/responses/BadRequest'

        '500':
          $ref: '#/components/responses/InternalServerError'

components:
  responses:
    BadRequest:
      description: bad request
    InternalServerError:
      description: internal server error
      content:
        #        application/json: - asta o rezolvat
        #        '*/*':
        application/json:
          schema:
            type: string
            description: Internal Server Error
  schemas:
    BalanceSnapshotDTO:
      type: object
      required:
        - balance
      properties:
        balance:
          type: number
          format: float
          example: 123.45
          description: The balance value with 2 decimal points.

    GreetingDTO:
      type: object
      required:
        - id
        - companyId
      properties:
        id:
          type: string
          format: uuid
        companyId:
          type: string
        content:
          type: string
        autoProcure:
          type: boolean
